name: growell_project
description: "A new Flutter project."

# This line prevents accidental publishing of your project to pub.dev.
publish_to: 'none'

# Version number for your app: major.minor.patch+build.
version: 1.0.0+1

# The Dart SDK version your project supports.
environment:
  sdk: ^3.6.0

# Dependencies required for the project to work.
dependencies:
  flutter:
    sdk: flutter  # The core Flutter SDK.
  cupertino_icons: ^1.0.8  # iOS-style icons.
  go_router: ^14.6.2  # A package for routing in Flutter apps.
  provider: ^6.1.2

# Dependencies used during development or testing.
dev_dependencies:
  flutter_test:
    sdk: flutter  # For writing and running Flutter tests.
  flutter_lints: ^5.0.0  # Recommended lints to enforce good coding practices.

# Flutter-specific configuration.
flutter:
  # Ensures the Material Icons font is included for the Material Icons class.
  uses-material-design: true

  # Adding assets to the project.
  assets:
    - assets/ 


  # Additional configuration for resolution-aware images can be added here.
  # For details: https://flutter.dev/docs/development/ui/assets-and-images
